name: Discord Alert

on:
  push:
    branches:
      - main

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Send Discord notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: |
            Novo push na branch main
            Repositorio: ${{ github.repository }}
            Autor: ${{ github.actor }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.event.head_commit.message }}
            Link: ${{ github.event.head_commit.url }}
